name: Auto Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.repo;
            const prNumber = context.payload.pull_request.number;
            await github.rest.pulls.requestReviewers({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: prNumber,
             reviewers: ["ahmeterloodos", "merttoptas", "aslansariloodos"]
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}

