name: Auto Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto Assign Reviewers
        uses: peter-evans/auto-assign-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ahmeterloodos,merttoptas,aslansariloodos



