name: Auto Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v5
        with:
          script: |
            const { repo, pull_request: { number } } = context;
            await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
              owner: repo.owner,
              repo: repo.repo,
              pull_number: number,
              reviewers: ["ahmeterloodos", "merttoptas", "aslansariloodos"]
            });
          token: ${{ secrets.GITHUB_TOKEN }}




